### ISSUE TITLE
[BUG] Release-Deploy Workflow is failing

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#916]
## Detailed description

SassDocs Site Deploy is failing during the Release Deploy workflow. 

### Failing information

This particular line was of interest:
`remote: Node.js v17.0.0`

[GitHub Workflow direct link to log of failure](https://github.com/Kajabi/sage-lib/runs/3954853172?check_suite_focus=true#step:18:4351)

<details>
  <summary>Expand for details from workflow failure</summary>
  
```
Error: error:0308010C:digital envelope routines::unsupported        
remote:     at new Hash (node:internal/crypto/hash:67:19)        
remote:     at Object.createHash (node:crypto:130:10)        
remote:     at module.exports (/tmp/build_07cbfaf8/node_modules/webpack/lib/util/createHash.js:135:53)        
remote:     at NormalModule._initBuildHash (/tmp/build_07cbfaf8/node_modules/webpack/lib/NormalModule.js:417:16)        
remote:     at handleParseError (/tmp/build_07cbfaf8/node_modules/webpack/lib/NormalModule.js:471:10)        
remote:     at /tmp/build_07cbfaf8/node_modules/webpack/lib/NormalModule.js:503:5        
remote:     at /tmp/build_07cbfaf8/node_modules/webpack/lib/NormalModule.js:358:12        
remote:     at /tmp/build_07cbfaf8/node_modules/loader-runner/lib/LoaderRunner.js:373:3        
remote:     at iterateNormalLoaders (/tmp/build_07cbfaf8/node_modules/loader-runner/lib/LoaderRunner.js:214:10)        
remote:     at iterateNormalLoaders (/tmp/build_07cbfaf8/node_modules/loader-runner/lib/LoaderRunner.js:221:10)        
remote:     at /tmp/build_07cbfaf8/node_modules/loader-runner/lib/LoaderRunner.js:236:3        
remote:     at context.callback (/tmp/build_07cbfaf8/node_modules/loader-runner/lib/LoaderRunner.js:111:13)        
remote:     at Object.loader (/tmp/build_07cbfaf8/node_modules/css-loader/dist/index.js:183:3) {        
remote:   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],        
remote:   library: 'digital envelope routines',        
remote:   reason: 'unsupported',        
remote:   code: 'ERR_OSSL_EVP_UNSUPPORTED'        
remote: }        
remote: 
remote: Node.js v17.0.0        
remote: error Command failed with exit code 1.        
remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.        
remote: 
remote: -----> Build failed        
remote:                
remote:        We're sorry this build is failing! You can troubleshoot common issues here:        
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys        
remote:                
remote:        Some possible problems:        
remote:                
remote:        - Dangerous semver range (>) in engines.node        
remote:          https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version        
remote:                
remote:        Love,        
remote:        Heroku        
remote:                
remote:  !     Push rejected, failed to compile Node.js app.        
remote: 
remote:  !     Push failed        
remote:  !        
remote:  ! ## Warning - The same version of this code has already been built: 6072b12037bb945420666292eb42a46d9864a69e        
remote:  !        
remote:  ! We have detected that you have triggered a build from source code with version 6072b12037bb945420666292eb42a46d9864a69e        
remote:  ! at least twice. One common cause of this behavior is attempting to deploy code from a different branch.        
remote:  !        
remote:  ! If you are developing on a branch and deploying via git you must run:        
remote:  !        
remote:  !     git push heroku <branchname>:main        
remote:  !        
remote:  ! This article goes into details on the behavior:        
remote:  !   https://devcenter.heroku.com/articles/duplicate-build-version        
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to ***.        
remote: 
To https://git.heroku.com/***.git
 ! [remote rejected]   6072b12037bb945420666292eb42a46d9864a69e -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/***.git'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```
</details>

---

### Attempted to resolve the Node version

[GitHub Workflow direct link to log of failed attempt to resolve](https://github.com/Kajabi/sage-lib/runs/3955438737?check_suite_focus=true#step:16:4303)

**Attempt to resolve was unsuccessful**, particularly this line:
`remote:        error @kajabi/sage-assets@0.51.2: The engine "node" is incompatible with this module. Expected version "14.x". Got "12.16.2" `

<details>
  <summary>Expand for details from attempt to resolve workflow failure</summary>
  
```
remote:        Cleaning up the bundler cache.        
remote: -----> Installing node-v12.16.2-linux-x64        
remote: -----> Installing yarn-v1.22.4        
remote: -----> Detecting rake tasks        
remote: -----> Preparing app for Rails asset pipeline        
remote:        Running: rake assets:precompile        
remote:        yarn install v1.22.4        
remote:        info No lockfile found.        
remote:        [1/4] Resolving packages...        
remote:        warning @rails/webpacker > node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142        
remote:        warning @rails/webpacker > node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142        
remote:        warning @rails/webpacker > node-sass > node-gyp > tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.        
remote:        warning @rails/webpacker > node-sass > request > har-validator@5.1.5: this library is no longer supported        
remote:        warning @rails/webpacker > node-sass > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.        
remote:        warning @rails/webpacker > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.        
remote:        warning @rails/webpacker > postcss-preset-env > postcss-color-gray > postcss-values-parser > flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.        
remote:        warning @rails/webpacker > webpack > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.        
remote:        warning @rails/webpacker > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.        
remote:        warning @rails/webpacker > optimize-css-assets-webpack-plugin > cssnano > cssnano-preset-default > postcss-svgo > svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.        
remote:        warning @rails/webpacker > webpack > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated        
remote:        warning @rails/webpacker > webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated        
remote:        warning left-pad@1.3.0: use String.prototype.padStart()        
remote:        warning resolve-url-loader > rework > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated        
remote:        warning webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.        
remote:        warning webpack-dev-server > sockjs > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.        
remote:        warning webpack-dev-server > webpack-log > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.        
remote:        [2/4] Fetching packages...        
remote:        error @kajabi/sage-assets@0.51.2: The engine "node" is incompatible with this module. Expected version "14.x". Got "12.16.2"        
remote:        error Found incompatible module.        
remote:        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.        
remote:         
remote:  !        
remote:  !     Precompiling assets failed.        
remote:  !        
remote:  !     Push rejected, failed to compile Ruby app.        
remote: 
remote:  !     Push failed        
remote: Verifying deploy...
remote: 
remote: !	Push rejected to ***.        
remote: 
To https://git.heroku.com/***.git
 ! [remote rejected]   758f2602a575ab4745b8098dc81f1d31866b5b5a -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/***.git'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.

```
</details>

**Comment by monicawheeler** [comment]
Resolved.
